Ahyoon
LandvibeDev/todo-backend pull request #2
Opened 2020-07-24 14:02 UTC by ahyoon99

GET/todo/cards/{cardId} 구현, NotFoundException 구현, ExceptionController(GlobalExceptionHandler)구현

2020-07-24 14:36 UTC, so3500 reviewed
미사용 주석은 과감하게 삭제하기

2020-07-24 14:36 UTC, so3500 commented on src/main/java/todo/backend/service/CardService.java
> +//	}
사용하지 않을 코드는 아예 삭제하는 것도 좋아. (코드 주석이 너무 많이 쌓이면 나중에 로직 파악에 방해가 될 수 있음)
그리고 커밋 히스토리에 변경사항이 남아서 나중에 필요할 때 참고해서 코드 추가하면돼
```suggestion
```

2020-07-24 14:36 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +		//return new ArrayList<>(cachedCards.values());
카드목록을 우선순위 오름차순으로 리턴하기 때문에 이 주석도 삭제해도 좋을 것 같아

2020-07-24 14:41 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +		}
카드 검사로직이 다른곳에도 많이 사용 되니까 함수로 빼서 코드중복을 줄이면 좋을 것 같아

2020-07-24 14:41 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +		}
.

2020-07-24 14:41 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +			throw new NotFoundException(id);
.

2020-07-24 14:41 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +		}
중복코드 줄여보기

2020-07-24 14:49 UTC, so3500 commented on src/main/java/todo/backend/TodoApplication.java
> +import org.springframework.beans.factory.UnsatisfiedDependencyException;
미사용 코드는 import 하지 않기

2020-07-24 14:49 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
> +			}
자바에서 객체 정렬 기준을 정하는 방법은 크게 2가지가 있어
1. Comparable 인터페이스 구현
2. Comparator 객체 사용

지금 이 코드는 Comparator 익명 객체를 사용해서 구현하고 있는데, 람다 함수나 스트림 정렬로 좀 더 코드를 간단하게 짤 수 있어
(참고. https://www.daleseo.com/java-comparable-comparator/)

2020-07-24 14:49 UTC, so3500 requested changes
lombok 적용하면 다시한번 볼게ㅎㅎ

2020-07-25 00:39 UTC, so3500 commented on src/main/java/todo/backend/repository/CardRepository.java
>  			);
카드 우선순위 값 검증은 컨트롤러 단에서 하고있어서 중복 검사할 필요는 없을 것 같아

2020-07-25 05:14 UTC, raccoonback approved these changes
Validation, Exception 잘 적용한 거 같아 👍 

다만, 커밋하기 전에 Intellij에서 지원하는 "Import 정리",  "코드 자동 정렬" 한 번씩 적용해주면, 불필요한 파일 변경도 줄이고 코드 형식도 통일할 수 있어서 좋을 거 같아~

- Import 정리 : `Ctrl + Alt + o`
- 코드 자동 정렬 : `Ctrl + Alt + l`

2020-07-25 05:14 UTC, raccoonback commented on src/main/java/todo/backend/repository/CardRepository.java
> +		return savedCard;
불필요한 savedCard 변수 제거해도 좋을거 같아~(굳이 변경하지 않아도 됨)
`return cachedCards.get(id);`

2020-07-25 13:21 UTC, so3500 approved these changes
고생했어~
아직 확인 못한 코멘트만 한번씩 봐줘 👍

2020-08-21 13:05 UTC, merged